### ISSUE TITLE
HTTP PUT method

### ISSUE THREAD

**Issue by kirrg001** [Telerik-Verified-Plugins/SecureHTTP#11]
Hey!

Nice Plugin, but why is there no PUT or DELETE HTTP method?

Thank you!
Kirrg

**Comment by EddyVerbruggen** [comment]
Because the [original authors of this plugin](https://github.com/wymsee/cordova-HTTP) didn't need it.

[Check these issues](https://github.com/wymsee/cordova-HTTP/search?q=put&type=Issues&utf8=%E2%9C%93) and add a comment if you'd like.
