### ISSUE TITLE
com.telerik.afnetworking offline

### ISSUE THREAD

**Issue by ManuelOverdijk** [Telerik-Verified-Plugins/SecureHTTP#16]
The plugin cannot be installed because npm package com.telerik.afnetworking is offline

```
Error: Failed to fetch plugin com.telerik.afnetworking via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.telerik.afnetworking
```

**Comment by EddyVerbruggen** [comment]
@ligaz do you have any idea why that npm package was removed perhaps?

**Comment by dfilip** [comment]
Any news on this? I couldn't work on my app all weekend because I couldn't setup my dev env.

**Comment by ManuelOverdijk** [comment]
@dfilip It's only the iOS dependencies are offline, so If you are only developing for Android you are good to go (just make sure that you havent' added iOS as a cordova platform)

**Comment by EddyVerbruggen** [comment]
Forgot to update: this has been fixed a few weeks ago in [this changeset](https://github.com/Telerik-Verified-Plugins/SecureHTTP/commit/3034a3d73273df93a57296d4c3ef7f5fe3d8ee4b)
