### ISSUE TITLE
compile error in iOS: 'Cordova/CDVJSON.h' file not found

### ISSUE THREAD

**Issue by chrstr** [Telerik-Verified-Plugins/SecureHTTP#18]
'Cordova/CDVJSON.h' file not found
#import &lt;Cordova/CDVJSON.h&gt;

This is using Cordova 6.2.0. Removing this statement in CordovaHttpPlugin.h compiles, is this being used?

**Comment by EddyVerbruggen** [comment]
Thanks for the report and suggested fix. I guess it's a leftover from way back, so I've removed it from the code.

**Comment by chrstr** [comment]
Thanks!
