### ISSUE TITLE
client cert?

### ISSUE THREAD

**Issue by pliablepixels** [Telerik-Verified-Plugins/SecureHTTP#22]
Hello there, is it possible to use this plugin to work with client certificates? My app won't know the certificate that needs to be accepted, so I can't really store any certificates in my root/assets folder.
As of today, any sites that need client certificates don't work on iOS or Android devices using cordova - they work well using regular browsers though.

**Comment by EddyVerbruggen** [comment]
Nope, not that I'm aware. Perhaps ask around on StackOverflow.
