### ISSUE TITLE
android: acceptAllCerts doesn't call callbacks

### ISSUE THREAD

**Issue by denisbabineau** [Telerik-Verified-Plugins/SecureHTTP#7]
As per API/doc, acceptAllCerts should call one of its success/failure callback but it's not doing so. At least on android, the CordovaHttpPlugin's execute method is not calling  success()/error() on callbackContext for the "acceptAllCerts" as it is doing for the "enableSSLPinning" case.

**Comment by EddyVerbruggen** [comment]
You're right, it didn't on Android. It will now invoke the success handler once it's done.

**Comment by denisbabineau** [comment]
awesome, thanks!
